os: linux
services:
  - docker
jobs:
  include:
    - stage: Build and Test
      language: python
      python: 3.6
      install: pip install -U pip
      script: bash actions-run-tests.sh && make docker-build
